version: '4'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    networks:
      - app-network
    restart: unless-stopped
    environment:
      - APP_ENV=production
    deploy:
      replicas: 2  # Para escalar la API si es necesario

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - app-network
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis_dm
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    networks:
      - app-network
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    networks:
      - app-network
    restart: unless-stopped
    command: ["php", "artisan", "queue:work"]
    depends_on:
      - redis
      - php



  upload:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: upload-service
    volumes:
      - ./:/var/www
    networks:
      - app-network
    depends_on:
      - redis
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
